# Generated by Django 2.0.7 on 2018-07-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='birth_date',
            field=models.CharField(help_text='Use the following format: dd/mm/yyyy', max_length=50, null=True),
        ),
    ]
