# Generated by Django 2.0.7 on 2018-07-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180721_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name (e.g. Warner Bros)', max_length=150)),
                ('city', models.CharField(help_text='Enter the city name (e.g. Los Angeles)', max_length=150)),
            ],
        ),
    ]
