# Generated by Django 2.0.7 on 2018-07-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=80)),
                ('actors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.People')),
                ('studio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Studio')),
            ],
        ),
    ]
