# Generated by Django 2.0.7 on 2018-07-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(to='api.People'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(help_text='Enter the name (e.g. Christopher Nolan)', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(help_text='Enter the name (e.g. Warner Bros)', max_length=150, primary_key=True, serialize=False),
        ),
    ]
