# Generated by Django 2.0.7 on 2018-07-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180721_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.People'),
        ),
    ]
