# Generated by Django 2.0.7 on 2018-07-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180721_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='people', to='api.People'),
        ),
    ]
